resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/22.yaml

packages:
- dyna
- dyna-brick
- dyna-gloss

extra-deps:
- brick-0.66.1
- temporal-media-0.6.3


# flags: {}

